version: '3'
services:
    web:
      image: nginx:latest
      ports:
          - "80:80"
      volumes:
          - ./public_html/:/public_html
          - ./conf.d:/etc/nginx/conf.d
      networks:
          - nginxphp
      links:
          - php

    php:
      image: php:7-fpm
      build:
        context: ./php
        dockerfile: DockerFile
      volumes:
        - ./public_html:/public_html
      links:
        - mysql
      networks:
        - nginxphp
      ports:
        - "9000:9000"
      expose:
        - "9000"

    mysql:
      image: mysql:latest
      volumes:
        - ./db:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 3306:3306
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
      networks:
        - nginxphp
    
    redis:
        image: redis:latest
        volumes:
          - ./redis:/redis
        ports:
          - "6379:6379"
        depends_on:
          - php
        networks:
          - nginxphp
    
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.0.2
      links:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
          - 81:80
      volumes:
          - ./localfolder/sessions:/sessions
      networks:
        - nginxphp

networks:
     nginxphp: